name: Bruno Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-bruno-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Run Bruno tests
        run: |
          npx bru run bruno --env environments/todo-dev-env.json --reporter spec