name: Bruno Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Start backend
        run: |
          ./gradlew bootRun &
          sleep 25

      - name: Run Bruno tests
        run: |
          cd bruno
          bru run bruno \
            --env environments/todo-dev-env \
            --bail